name: pub_download
version: 0.0.1
description: A simple scraper of pub.dartlang.org.
author: Filip Hracek <filip.hracek@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  sqlite: ^0.4.0

#dev_dependencies:
#  test: '>=0.12.0 <0.13.0'
